# prospector configuration

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: false

ignore-paths:
  - tests
  - orangearg/argument/graph
  - orangearg/argument/widgets

pyroma:
  run: true

pycodestyle:
  disable:
    - E501  # line too long

pylint:
  disable:
    - line-too-long
    - invalid-name
    - too-many-arguments  # chunker.py::TopicModel::init_model
