language: python

dist: xenial

addons:
    apt:
        packages:
            - libxkbcommon-x11-0  # for PyQt 5.12
            - libxcb-icccm4
            - libxcb-image0
            - libxcb-keysyms1
            - libxcb-randr0
            - libxcb-render-util0
            - libxcb-xinerama0

matrix:
  include:
    - python: '3.6'
      env: ORANGE="3.25.1"

    - python: '3.7'
      env: ORANGE="release"

    - python: '3.8'
      env: ORANGE="release"

    - python: '3.9'
      env: ORANGE="master"

cache:
    apt: true
    pip: true

before_install:
    - pip install -U pip wheel setuptools
    - pip install codecov

install:
    - pip install sip pyqt5 pyqtwebengine
    - source $TRAVIS_BUILD_DIR/.travis/install_orange.sh
    - pip install -e .

script:
    - export XVFBARGS="-screen 0 1280x1024x24"
    - catchsegv xvfb-run -a -s "$XVFBARGS" coverage run -m unittest discover -v

after_success:
    - codecov
