name: linting

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
    - 'dev_*'

jobs:
  ruff:
    name: lint with ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
      