name: Build and publish Python distribution to PyPI and TestPyPI

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install build
        run: python3 -m pip install build
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist/

  publish-to-pypi:
    name: Publish distribution to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    environment:
      name: pypi
      url: https://pypi.org/p/orangearg
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-test_pypi:
    name: Publish distribution to Test PyPI
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    environment:
      name: testpypi
      url: https://test.pypi.org/p/orangearg
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist/
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
