name: sonarcloud analysis

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
    - 'dev_*'

jobs:
  sonarcloud:
    name: SonarCloud scan
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: setup.cfg

      - name: Upgrade and install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install .[dev]

      - name: Run tests with coverage
        run: pytest -v --cov=orangecontrib.argument.miner --cov-report term --cov-report xml:coverage.xml tests/ 

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}